#### Importing required libraries

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

#### Load the dataset

In [2]:
df = pd.read_csv("Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

#### Preprocess the data
#### Drop irrelevant columns

In [3]:
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis = 1)
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

#### Encode categorical variables
- Label Encode 'Gender' -> 0 or 1
- One Hot Encode 'Geography' -> each category becomes a new column

In [4]:
label_encoder_gender = LabelEncoder()
df['Gender'] = label_encoder_gender.fit_transform(df['Gender'])
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [5]:
onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(df[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [6]:
onehot_encoder_geo.get_feature_names_out(["Geography"])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [7]:
geo_encoder_df = pd.DataFrame(geo_encoder.toarray(), columns = onehot_encoder_geo.get_feature_names_out(["Geography"]))
geo_encoder_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

#### Combine one hot encoded columns with the original data

In [8]:
df = pd.concat([df.drop("Geography", axis = 1), geo_encoder_df], axis = 1)
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

#### Save the encoders in a pickle file

In [9]:
with open("label_encoder_gender.pkl", "wb") as file:
    pickle.dump(label_encoder_gender, file)

with open("onehot_encoder_geo.pkl", "wb") as file:
    pickle.dump(onehot_encoder_geo, file)

In [10]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

#### Independent and Dependent features

In [11]:
X = df.drop("Exited", axis = 1)
y = df['Exited']

#### Train Test Split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

#### Scaling the features

In [13]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#### Save the scaler in pickle file

In [14]:
with open("scaler.pkl", "wb") as file:
    pickle.dump(scaler, file)

### **ANN Implementation**

In [15]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

WARNING:tensorflow:From c:\Users\sourav\anaconda3\envs\envpy3.11\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

#### Build our ANN Model

In [16]:
model = Sequential([
    Dense(64, activation = "relu", input_shape = (X_train.shape[1], )),     ## 1st Hidden Layer connected with Input
    Dense(32, activation = "relu"),         ## 2nd Hidden Layer
    Dense(1, activation = "sigmoid"),       ## Output Layer
])

WARNING:tensorflow:From c:\Users\sourav\anaconda3\envs\envpy3.11\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [18]:
opt = tensorflow.keras.optimizers.Adam(learning_rate = 0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()
loss

#### Compile the Model

In [19]:
model.compile(optimizer = opt, loss = loss, metrics = ["accuracy"])

#### Set up the Tensorboard

In [20]:
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir = log_dir, histogram_freq = 1)

#### Set up Early Stopping

In [21]:
early_stopping_callback = EarlyStopping(monitor = "val_loss", patience = 10, restore_best_weights = True)

### **Training the Model**

In [22]:
history = model.fit(
    X_train,
    y_train,
    validation_data = (X_test, y_test),
    epochs = 100,
    callbacks = [tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\sourav\anaconda3\envs\envpy3.11\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\sourav\anaconda3\envs\envpy3.11\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 8s 13ms/step - loss: 0.3946 - accuracy: 0.8363 - val_loss: 0.3693 - val_accuracy: 0.8530
Epoch 2/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3565 - accuracy: 0.8553 - val_loss: 0.3514 - val_accuracy: 0.8590
Epoch 3/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3510 - accuracy: 0.8571 - val_loss: 0.3512 - val_accuracy: 0.8585
Epoch 4/100
250/250 [==============================] - 3s 11ms/step - loss: 0.3464 - accuracy: 0.8587 - val_loss: 0.3588 - val_accuracy: 0.8580
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3392 - accuracy: 0.8618 - val_loss: 0.3597 - val_accuracy: 0.8535
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3397 - accuracy: 0.8609 - val_loss: 0.3449 - val_accuracy: 0.8545
Epoch 7/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3348 - accuracy: 0.8646 - val_loss: 0.3475 - val_accuracy: 0.8545
Epoch 8/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3341 - accuracy: 0.8629 - val_loss: 0.3534 - val_accuracy: 0.8490
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3340 - accuracy: 0.8636 - val_loss: 0.3546 - val_accuracy: 0.8550
Epoch 10/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3274 - accuracy: 0.8654 - val_loss: 0.3507 - val_accuracy: 0.8515
Epoch 11/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3262 - accuracy: 0.8649 - val_loss: 0.3518 - val_accuracy: 0.8555
Epoch 12/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3245 - accuracy: 0.8654 - val_loss: 0.3505 - val_accuracy: 0.8555
Epoch 13/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3255 - accuracy: 0.8649 - val_loss: 0.3534 - val_accuracy: 0.8580
Epoch 14/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3190 - accuracy: 0.8679 - val_loss: 0.3787 - val_accuracy: 0.8505
Epoch 15/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3213 - accuracy: 0.8681 - val_loss: 0.3516 - val_accuracy: 0.8585
Epoch 16/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3158 - accuracy: 0.8698 - val_loss: 0.3517 - val_accuracy: 0.8570

#### Save the Model in h5 file

In [23]:
model.save("model.h5")

c:\Users\sourav\anaconda3\envs\envpy3.11\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

#### Load the Tensorboard

In [24]:
%load_ext tensorboard

In [ ]:
%tensorboard --logdir logs/fit/

Reusing TensorBoard on port 6006 (pid 3556), started 2:16:33 ago. (Use '!kill 3556' to kill it.)